# Generated by Django 3.2.8 on 2021-12-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='Order',
        ),
    ]
