# Generated by Django 3.2.8 on 2021-12-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_orders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Zipcode',
            new_name='zipcode',
        ),
    ]
