# Generated by Django 3.2.8 on 2021-12-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_zipcode_order_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
