# Generated by Django 3.2.8 on 2021-12-31 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_order_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalprice',
            new_name='total',
        ),
    ]
