# Generated by Django 3.2.8 on 2021-12-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_totalprice_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
