# Generated by Django 3.2.8 on 2021-12-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_order_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
    ]
